#!/bin/bash

ALOCAL=`sed -n 2p run.sh`
ONLINE=`wget --no-cache -qO - https://raw.githubusercontent.com/osrun/beta/master/run.sh | sed -n 2p`

echo $ALOCAL
echo $ONLINE


if ping google.com -c3 2> /dev/null; then
 echo "conexao ok"
if [[ $ALOCAL = $ONLINE ]]; then
  echo "Atualizado"
 else
  echo "Atualizar" 
fi

else
 echo "sem conexao"
fi
